# Basic configuration for Kong without the ingress controller, using the Postgres subchart
# This installation does not create an Ingress or LoadBalancer Service for
# the Admin API. It requires port-forwards to access without further
# configuration to add them, e.g.:
# kubectl port-forward deploy/your-deployment-kong 8001:8001

image:
  repository: claudioed/kong-oidc-jwt
  tag: latest

env:
  prefix: /kong_prefix/
  database: "off" # Não quero fazer a instalação usando um DB, mas o Kubernetes
  plugins: bundled,oidc,kong-jwt2header # Todos os plugins opensource + todos do oidc + do kong

admin:
  enabled: true
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001
  tls:
    parameters: []
  labels:
    enable-metrics: "true"

postgresql:
  enabled: false

# Vamos controlar tudo com o Ingress Controller
ingressController:
  enabled: true
  installCRDs: false

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8100"

proxy:
  type: NodePort

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
