apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bets-api
  annotations:
    kubernetes.io/ingress.class: "kong" # O Ingress será o Kong
    konghq.com/override: do-not-preserve-host
    konghq.com/plugins: oidc-bets
    #konghq.com/plugins: rl-by-header
    #konghq.com/plugins: prometheus-bets
spec:
  rules:
    - http:
        paths:
          - path: /api/bets
            pathType: Prefix
            backend:
              service:
                name: bets
                port:
                  number: 9999
